### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by GauriDhande** [hyperconnect/TC-ResNet#10]
I tried to run the code as described. Only changed some of the values of arguments. I'm getting an error:

Traceback (most recent call last):
  File "/home/gauri/TC-ResNet/evaluate_audio.py", line 87, in <module>
    main(args)
  File "/home/gauri/TC-ResNet/evaluate_audio.py", line 28, in main
    is_training,
  File "/home/gauri/TC-ResNet/datasets/audio_data_wrapper.py", line 17, in __init__
    self.setup_dataset(self.placeholders)
  File "/home/gauri/TC-ResNet/datasets/data_wrapper_base.py", line 70, in setup_dataset
    dataset = dataset.map(self._parse_function, num_parallel_calls=self.args.num_threads)
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1584, in map
    self, map_func, num_parallel_calls, preserve_cardinality=False))
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2771, in __init__
    input_dataset, map_func, use_inter_op_parallelism, preserve_cardinality)
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2737, in __init__
    map_func, self._transformation_name(), dataset=input_dataset)
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2124, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/framework/function.py", line 490, in add_to_graph
    self._create_definition_if_needed()
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/framework/function.py", line 341, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/framework/function.py", line 355, in _create_definition_if_needed_impl
    whitelisted_stateful_ops=self._whitelisted_stateful_ops)
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/framework/function.py", line 883, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2099, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/home/gauri/TC-ResNet/datasets/audio_data_wrapper.py", line 53, in _parse_function
    background_max_volume=self.background_max_volume,
  File "/home/gauri/TC-ResNet/datasets/audio_data_wrapper.py", line 35, in augment_audio
    return aug_fn(filename, desired_samples, file_format, sample_rate, **kwargs)
  File "/home/gauri/TC-ResNet/datasets/augmentation_factory.py", line 187, in anchored_slice_or_pad
    audio = _mix_background(audio, desired_samples, is_silent=is_silent, **kwargs)
  File "/home/gauri/TC-ResNet/datasets/augmentation_factory.py", line 66, in _mix_background
    }, exclusive=True)
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 4092, in case
    strict=strict)
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3968, in _case_helper
    pred_fn_pairs, exclusive, name, allow_python_preds)
  File "/home/gauri/anaconda2/envs/edgeml_gpu/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3933, in _case_verify_and_canonicalize_args
    predicates, actions = zip(*pred_fn_pairs)
ValueError: not enough values to unpack (expected 2, got 0)

Can anybody help me in solving the above error?
Thanks in advance.

**Comment by mudong0419** [comment]
I have the same error.

**Comment by mudong0419** [comment]
Solved, when convert the dataset with python google_speech_commmands_dataset_to_our_format_with_split.py, give the absolate path.
